export const colors = {
  white: "#fff",
  text: "#fff",
  background: "#000",
  onboardingBackground: "#15141A",
  buttonWhite: "#fff",
  darkText: "#000",
  tabIconDefault: "#ccc",
  gray: "#a5a5a5",
  buttonGray: "#302E38",
  purple: "#7b2cbf",
  gold: "#FFDA11",
  pink: "#E178C5",
  redLight: "#FF8E8F",
  orange: "#FFB38E",
  orangeLight: "#FFFDCB",
  red: "#c1121f",
  silver: "#8e939f",
  messageColor: "",
};
